# Import

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# from sklearn import linear_model

# Read File

In [4]:
df=pd.read_csv("convertnumber.csv")
df.head(157)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,className
0,30,1,0,0,0,0,0,0,0,0,0,0,0,1.0,85,18,4.0,61,0,1
1,50,0,0,0,1,0,0,0,0,0,0,0,0,0.9,135,42,3.5,61,0,1
2,78,0,1,0,1,0,0,1,0,0,0,0,0,0.7,96,32,4.0,61,0,1
3,31,0,1,1,0,0,0,1,0,0,0,0,0,0.7,46,52,4.0,80,0,1
4,34,0,1,0,0,0,0,1,0,0,0,0,0,1.0,85,200,4.0,61,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,46,0,1,0,1,1,1,1,0,0,1,1,1,7.6,85,242,3.3,50,1,0
151,44,0,1,0,1,0,0,1,1,0,0,0,0,0.9,126,142,4.3,61,1,1
152,61,0,0,0,1,1,0,0,1,0,1,0,0,0.8,75,20,4.1,61,1,1
153,53,1,0,0,1,0,0,1,0,1,1,0,1,1.5,81,19,4.1,48,1,1
154,43,0,1,0,1,0,0,1,0,1,1,1,0,1.2,100,19,3.1,42,1,0

In [5]:
colums = (df.columns[0])

In [6]:
max= [df[c].max() for c in df.columns] 
min= [df[c].min() for c in df.columns]

In [7]:
i=0
for c in df.columns:
    while(i<len(df.columns)): 
        df[c]=((df[c]-min[i])/(max[i]-min[i]))
        i=i+1
        break

In [8]:
arr = df.values
x_train=[]
y1=[]
a=df.shape
for i in range(a[0]):                      
    x_train.append((arr[i][:-1]).tolist())
    y1.append(arr[i][-1])

In [9]:
m=np.ones((155,1))
b=np.matrix(x_train)
b=np.concatenate((m,b),axis=1)     
d=b.T
e=np.linalg.inv(np.matmul(d,b))
y1=np.matrix(y1)
y1=y1.T
f=np.matmul(e,d)
c1=np.matmul(f,y1)

In [10]:
x_test=[[1],]
for j in range (19):
    inp=[float(input("Enter Value:"))]
    x_test.append(inp)
for i in range(19):
    x_test[i+1][0]=(x_test[i+1][0]-min[i])/(max[i]-min[i])
x_test=np.matrix(x_test)
Y1=np.matmul(c1.T,x_test)


# 43	0	1	0	1	0	0	1	0	1	1	1	0	1.2	100	19	3.1	42	1 die
# 53	1	0	0	1	0	0	1	0	1	1	0	1	1.5	81	19	4.1	48	1 live

Enter Value:43
Enter Value:0
Enter Value:1
Enter Value:0
Enter Value:1
Enter Value:0
Enter Value:0
Enter Value:1
Enter Value:0
Enter Value:1
Enter Value:1
Enter Value:1
Enter Value:0
Enter Value:1.2
Enter Value:100
Enter Value:19
Enter Value:3.1
Enter Value:42
Enter Value:1

In [17]:
result=((Y1*(max[-1]-min[-1]))+min[-1])
value= result

if value > 0.5 :
    print("Live")
else :
     print("Die")

Die

In [14]:
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
model =LinearRegression()
x,y=df[['age','sex','steroid','antivirals','fatigue','malaise','anorexia','liver_big','liver_firm','spleen_palpable','spiders','ascites','varices','bilirubin','alk_phosphate','sgot','albumin','protime','histology']], df.className
model.fit(x, y)
model.score(x, y)*100

48.13977157351673